In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect("level_3_final_project_library db")

In [3]:
def run(query):
    return pd.read_sql_query(query, conn)

In [4]:
library_sql_checkouts = pd.read_sql_query("SELECT * FROM checkouts", conn)
library_sql_checkouts.head()

   checkout_id  member_id  book_id checkout_date return_date
0         9263       1047      517    2024-10-21  2024-11-07
1         9340       1072      513    2025-08-24  2025-09-01
2         9231       1053      523    2024-02-04  2024-02-16
3         9129       1032      513    2025-06-21  2025-06-29
4         9370       1079      511    2025-11-11  2025-12-03

In [5]:
library_sql_books = pd.read_sql_query("SELECT * FROM books", conn)
library_sql_books.head()

   book_id                title         author
0      501      The Silver Kite  Amina Darwish
1      502       Desert Compass  Amina Darwish
2      503    The Lantern Maker   Adel Roushdy
3      504  Rooftop Astronomers   Adel Roushdy
4      505  Letters to the Nile      Aya Hafez

In [6]:
library_sql_members = pd.read_sql_query("SELECT * FROM members", conn)
library_sql_members.head()

,member_id,first_name,last_name,grade,neighborhood,membership_status,join_date
0,1001,Salma,Ibrahim,8.0,Maadi,Active,2023-04-05
1,1002,Fares,Saleh,9.0,Maadi,Active,None
2,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23
3,1004,Fares,Wahba,7.0,Maadi,inactive,2024-10-09
4,1005,Youssef,Halim,9.0,Maadi,Active,2024-05-05

In [7]:
query = '''
SELECT checkouts.member_id,
       members.first_name,
       members.last_name,
       COUNT(checkouts.member_id) AS checkouts_count

FROM checkouts

JOIN members ON checkouts.member_id = members.member_id

GROUP BY checkouts.member_id
ORDER BY checkouts.member_id DESC
'''

run(query)

    member_id first_name last_name  checkouts_count
0        1080     Bassel     Wahba                2
1        1079       Rana     Osman               10
2        1077       Lina    Rashad                6
3        1076       Dina     Wahba                7
4        1075      Malak     Fahmy                9
..        ...        ...       ...              ...
57       1006      Layla   Mansour                1
58       1005    Youssef     Halim                3
59       1003     Bassel    Hegazy                9
60       1002      Fares     Saleh                2
61       1001      Salma   Ibrahim                1

[62 rows x 4 columns]

In [8]:
query = '''
SELECT author,
       title
FROM books
WHERE title LIKE 'K%'
'''
run(query)

           author             title
0  Jasmine Wahdan  Kites Over Cairo

In [9]:
query = '''
SELECT books.title,
       checkouts.book_id,
       COUNT(checkouts.member_id) AS checkout_count

FROM checkouts

JOIN books ON checkouts.book_id = books.book_id

GROUP BY books.book_id
ORDER BY checkout_count DESC LIMIT 5;

'''
run(query)

                    title  book_id  checkout_count
0         The Silver Kite      501              57
1   Fossils and Fireflies      507              55
2  Circuits for Beginners      513              46
3        Kites Over Cairo      519              38
4    Storms and Sailboats      525              25

In [10]:
query = '''
SELECT books.title,
       checkouts.book_id,
       members.first_name,
       members.last_name,
       members.member_id,
       COUNT(checkouts.member_id) AS checkout_count

FROM checkouts

JOIN books ON checkouts.book_id = books.book_id
JOIN members ON checkouts.member_id = members.member_id

GROUP BY books.book_id
ORDER BY checkout_count DESC LIMIT 10;

'''
run(query)

,title,book_id,first_name,last_name,member_id,checkout_count
0,The Silver Kite,501,Nour,Nabil,1010,57
1,Fossils and Fireflies,507,Mostafa,Fouad,1027,55
2,Circuits for Beginners,513,Seif,Zaki,1072,46
3,Kites Over Cairo,519,Nada,Rashad,1041,38
4,Storms and Sailboats,525,Sherif,Saleh,1044,25
5,The Paper Boat Club,506,Youssef,Hegazy,1024,14
6,Riddles of the Red Sea,529,Mostafa,Fouad,1027,12
7,The Beekeeper's Almanac,516,Lina,Halim,1059,12
8,Marbles and Mirrors,509,Nada,Rashad,1041,9
9,The Last Bookmark,532,Mostafa,Fouad,1027,8

In [11]:
query = '''
SELECT checkouts.book_id,
       members.first_name,
       members.last_name,
       members.member_id,
       members.neighborhood,
       checkouts.checkout_date,
       COUNT(checkouts.member_id) AS checkout_count

FROM checkouts

JOIN books ON checkouts.book_id = books.book_id
JOIN members ON checkouts.member_id = members.member_id

WHERE members.neighborhood = 'Maadi'

GROUP BY checkouts.checkout_date
ORDER BY checkouts.checkout_date DESC LIMIT 10 OFFSET 10;

'''
run(query)

,book_id,first_name,last_name,member_id,neighborhood,checkout_date,checkout_count
0,513,Bassel,Hegazy,1003,Maadi,2025-09-04,1
1,502,Adam,Badr,1017,Maadi,2025-08-25,1
2,501,Ziad,Saleh,1008,Maadi,2025-08-23,1
3,521,Bassel,Hegazy,1003,Maadi,2025-08-21,1
4,525,Ahmed,Shafik,1018,Maadi,2025-08-19,1
5,525,Hamza,Sabry,1015,Maadi,2025-08-08,1
6,503,Ahmed,Shafik,1018,Maadi,2025-08-04,1
7,519,Ziad,Fouad,1013,Maadi,2025-07-27,1
8,513,Bassel,Hegazy,1003,Maadi,2025-07-22,2
9,516,Ziad,Saleh,1008,Maadi,2025-07-20,1

In [12]:
checkouts = run("SELECT * FROM checkouts")
members = run("SELECT * FROM members")

combined = pd.merge(checkouts, members, on='member_id')

In [13]:
combined

,checkout_id,member_id,book_id,checkout_date,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date
0,9263,1047,517,2024-10-21,2024-11-07,Sara,Rashad,NaN,Heliopolis,Inactive,2024-06-25
1,9340,1072,513,2025-08-24,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21
2,9231,1053,523,2024-02-04,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03
3,9129,1032,513,2025-06-21,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19
4,9370,1079,511,2025-11-11,2025-12-03,Rana,Osman,8.0,Shubra,Active,2024-10-27
...,...,...,...,...,...,...,...,...,...,...,...
386,9232,1044,513,2025-05-26,2025-06-11,Sherif,Saleh,7.0,Heliopolis,active,2024-02-19
387,9084,1008,511,2024-06-27,2024-07-22,Ziad,Saleh,8.0,Maadi,active,2025-10-28
388,9116,1024,519,2025-01-10,2025-02-09,Youssef,Hegazy,8.0,Nasr City,inactive,2024-01-04
389,9352,1076,501,2025-02-02,None,Dina,Wahba,7.0,Shubra,Active,2025-12-13
390,9246,1044,529,2025-06-25,2025-07-04,Sherif,Saleh,7.0,Heliopolis,active,2024-02-19

In [14]:
json = pd.read_json("/content/level_3_final_project_library json")
json.head()

   book_id       genre  pages  publication_year            publisher
0      501   Adventure    128            2017.0           Nile Press
1      502   Adventure    109            2018.0          Delta House
2      503  Historical    259               NaN           Nile Press
3      504     Science    319            2009.0  Cairo Young Readers
4      505  Historical    216            2024.0          Oasis Books

In [15]:
book_catalog = pd.merge(combined, json, on='book_id', how='inner')

In [16]:
book_catalog.head()

,checkout_id,member_id,book_id,checkout_date,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher
0,9263,1047,517,2024-10-21,2024-11-07,Sara,Rashad,NaN,Heliopolis,Inactive,2024-06-25,Mystery,338,2015.0,Delta House
1,9340,1072,513,2025-08-24,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Science,294,2021.0,Oasis Books
2,9231,1053,523,2024-02-04,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,Historical,276,2018.0,Oasis Books
3,9129,1032,513,2025-06-21,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19,Science,294,2021.0,Oasis Books
4,9370,1079,511,2025-11-11,2025-12-03,Rana,Osman,8.0,Shubra,Active,2024-10-27,Historical,117,2016.0,Nile Press

In [17]:
data_unifaction = pd.read_html("/content/level_3_final_project_library html")[0]
data_unifaction.head()

   Member ID  Book ID Checkout Date
0       1026      522    2025-07-11
1       1049      520    2025-07-11
2       1062      525    2025-07-05
3       1065      520    2025-07-07
4       1104      515    2025-07-07

In [18]:
book_catalog['member_id'].head()

0    1047
1    1072
2    1053
3    1032
4    1079
Name: member_id, dtype: int64

In [19]:
data_unifaction.columns = ["member_id", "book_id", "checkout_date"]
data_unifaction['member_id'].head()

0    1026
1    1049
2    1062
3    1065
4    1104
Name: member_id, dtype: int64

In [20]:
book_catalog['member_id']=data_unifaction['member_id']

In [21]:
data_unifaction.columns = ["member_id", "book_id", "checkout_date"]
data_unifaction['member_id'].max()

1201

In [22]:
data_unifaction['member_id'].head()

0    1026
1    1049
2    1062
3    1065
4    1104
Name: member_id, dtype: int64

In [23]:
book_catalog['member_id'].isna().sum()

np.int64(365)

In [24]:
book_catalog['member_id']=book_catalog['member_id'].fillna(book_catalog['member_id'].median())

In [25]:
book_catalog['member_id']=book_catalog['member_id'].astype(int)

In [26]:
book_catalog['member_id'].max()

1201

In [27]:
book_catalog['member_id'].head()

0    1026
1    1049
2    1062
3    1065
4    1104
Name: member_id, dtype: int64

In [28]:
data_unifaction['checkout_date'].duplicated().sum()

np.int64(18)

In [29]:
data_unifaction[data_unifaction['checkout_date'].duplicated()]

    member_id  book_id checkout_date
1        1049      520    2025-07-11
4        1104      515    2025-07-07
6        1063      522    2025-07-07
8        1029      523    2025-07-09
10       1005      513    2025-07-10
11       1104      526    2025-07-05
13       1002      521    2025-07-08
14       1150      530    2025-07-10
15       1041      504    2025-07-05
16       1055      526    2025-07-11
18       1012      509    2025-07-11
19       1007      510    2025-07-07
20       1073      530    2025-07-07
21       1003      501    2025-07-08
22       1017      507    2025-07-11
23       1061      504    2025-07-06
24       1201      523    2025-07-08
25       1041      512    2025-07-06

In [30]:
data_unifaction = data_unifaction.drop_duplicates(subset='member_id')

In [31]:
data_unifaction = data_unifaction.drop_duplicates(subset='book_id')

In [32]:
data_unifaction['member_id'].unique()

array([1026, 1049, 1062, 1104, 1009, 1022, 1029, 1201, 1005, 1058, 1002,
       1150, 1041, 1055, 1007, 1003, 1017])

In [33]:
book_catalog['member_id'].unique()

array([1026, 1049, 1062, 1065, 1104, 1009, 1063, 1022, 1029, 1201, 1005,
       1058, 1002, 1150, 1041, 1055, 1061, 1012, 1007, 1073, 1003, 1017,
       1052])

In [34]:
book_catalog['member_id'].value_counts()

member_id
1052    365
1201      2
1104      2
1041      2
1061      2
1049      1
1026      1
1063      1
1009      1
1065      1
1062      1
1005      1
1058      1
1029      1
1022      1
1150      1
1002      1
1012      1
1055      1
1007      1
1073      1
1003      1
1017      1
Name: count, dtype: int64

In [35]:
book_catalog['member_id']=book_catalog['member_id'].drop_duplicates()

In [36]:
book_catalog['member_id'].value_counts()

member_id
1026.0    1
1049.0    1
1062.0    1
1065.0    1
1104.0    1
1009.0    1
1063.0    1
1022.0    1
1029.0    1
1201.0    1
1005.0    1
1058.0    1
1002.0    1
1150.0    1
1041.0    1
1055.0    1
1061.0    1
1012.0    1
1007.0    1
1073.0    1
1003.0    1
1017.0    1
1052.0    1
Name: count, dtype: int64

In [37]:
book_catalog['member_id'].isna().sum()

np.int64(368)

In [38]:
book_catalog['member_id'] = book_catalog['member_id'].fillna(book_catalog['member_id'].median())

In [39]:
book_catalog['member_id'].value_counts()

member_id
1049.0    369
1026.0      1
1062.0      1
1065.0      1
1104.0      1
1009.0      1
1063.0      1
1022.0      1
1029.0      1
1201.0      1
1005.0      1
1058.0      1
1002.0      1
1150.0      1
1041.0      1
1055.0      1
1061.0      1
1012.0      1
1007.0      1
1073.0      1
1003.0      1
1017.0      1
1052.0      1
Name: count, dtype: int64

In [40]:
book_catalog.shape

(391, 15)

In [41]:
data_unifaction['member_id'].isna().sum()

np.int64(0)

In [42]:
data_unifaction.shape

(17, 3)

In [43]:
data_unifaction['member_id'].value_counts()

member_id
1026    1
1049    1
1062    1
1104    1
1009    1
1022    1
1029    1
1201    1
1005    1
1058    1
1002    1
1150    1
1041    1
1055    1
1007    1
1003    1
1017    1
Name: count, dtype: int64

In [44]:
#beacause the column member_id is exist at the 2 tables I have to drop 1 from them so I will drop the member_id from table data_unifaction because it has the same members id at table book_catalog but column member_id at table book_catalog has more members id than table data_unifaction
data_unifaction.columns = ["member_id", "book_id", "checkout_date"]
final_combined = pd.merge(data_unifaction,book_catalog.drop('member_id', axis=1), on='book_id', how='inner')
final_combined

,member_id,book_id,checkout_date_x,checkout_id,checkout_date_y,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher
0,1026,522,2025-07-11,9033,2025-02-26,2025-03-11,Rana,Fouad,6.0,Maadi,Active,2025-12-04,Mystery,104,2016.0,Cairo Young Readers
1,1026,522,2025-07-11,9274,2024-09-06,2024-09-17,Retaj,Fahmy,6.0,Heliopolis,Inactive,2024-03-21,Mystery,104,2016.0,Cairo Young Readers
2,1026,522,2025-07-11,9332,2024-07-03,None,Tarek,Adel,7.0,Zamalek,Active,2023-01-22,Mystery,104,2016.0,Cairo Young Readers
3,1026,522,2025-07-11,9121,2025-02-24,2025-03-14,Mostafa,Fouad,9.0,Nasr City,Active,2023-09-25,Mystery,104,2016.0,Cairo Young Readers
4,1026,522,2025-07-11,9314,2024-08-13,2024-09-02,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Mystery,104,2016.0,Cairo Young Readers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,1017,507,2025-07-11,9377,2025-03-25,2025-04-06,Aya,Wahba,9.0,Nasr City,Active,2025-01-22,Science,160,2024.0,Nile Press
256,1017,507,2025-07-11,9210,2025-09-11,2025-09-29,Sherif,Saleh,7.0,Heliopolis,active,2024-02-19,Science,160,2024.0,Nile Press
257,1017,507,2025-07-11,9028,2025-01-19,2025-01-28,Adam,Badr,9.0,Maadi,Active,2025-07-12,Science,160,2024.0,Nile Press
258,1017,507,2025-07-11,9311,2025-06-26,2025-07-09,Adam,Fahmy,6.0,Zamalek,Active,2025-07-12,Science,160,2024.0,Nile Press
259,1017,507,2025-07-11,9164,2024-12-02,2024-12-12,Aya,Wahba,9.0,Nasr City,Active,2025-01-22,Science,160,2024.0,Nile Press

In [46]:
final_combined["member_id"].isna().sum()

np.int64(0)

In [47]:
final_combined.shape

(260, 16)

In [48]:
final_combined.isna().sum()

member_id             0
book_id               0
checkout_date_x       0
checkout_id           0
checkout_date_y       0
return_date          48
first_name            0
last_name             0
grade                23
neighborhood          0
membership_status     0
join_date             4
genre                 0
pages                 0
publication_year      8
publisher             0
dtype: int64

In [49]:
final_combined.shape

(260, 16)

In [50]:
final_combined["return_date"]=final_combined["return_date"].fillna(final_combined["return_date"].mode()[0])
final_combined["join_date"]=final_combined["join_date"].fillna(final_combined["join_date"].mode()[0])
final_combined["publication_year"]=final_combined["publication_year"].fillna(final_combined["publication_year"].median())
final_combined["last_name"]=final_combined["last_name"].fillna(final_combined["last_name"].mode()[0])
final_combined["grade"]=final_combined["grade"].fillna(final_combined["grade"].median())

In [51]:
final_combined=final_combined.dropna(subset=["pages"])

In [52]:
final_combined["pages"].isna().sum()

np.int64(0)

In [53]:
final_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   member_id          260 non-null    int64
 1   book_id            260 non-null    int64
 2   checkout_date_x    260 non-null    object
 3   checkout_id        260 non-null    int64
 4   checkout_date_y    260 non-null    object
 5   return_date        260 non-null    object
 6   first_name         260 non-null    object
 7   last_name          260 non-null    object
 8   grade              260 non-null    float64
 9   neighborhood       260 non-null    object
 10  membership_status  260 non-null    object
 11  join_date          260 non-null    object
 12  genre              260 non-null    object
 13  pages              260 non-null    int64
 14  publication_year   260 non-null    float64
 15  publisher          260 non-null    object
dtypes: float64(2), int64(4), object(10)
memory usage: 32.6+ KB

In [54]:
final_combined.isna().sum()

member_id            0
book_id              0
checkout_date_x      0
checkout_id          0
checkout_date_y      0
return_date          0
first_name           0
last_name            0
grade                0
neighborhood         0
membership_status    0
join_date            0
genre                0
pages                0
publication_year     0
publisher            0
dtype: int64

In [55]:
final_combined.duplicated().sum()

np.int64(4)

In [56]:
final_combined.shape

(260, 16)

In [57]:
final_combined[final_combined.duplicated()]

,member_id,book_id,checkout_date_x,checkout_id,checkout_date_y,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher
111,1005,513,2025-07-10,9194,2024-09-17,2024-10-09,Youssef,Hegazy,8.0,Nasr City,inactive,2024-01-04,Science,294,2021.0,Oasis Books
180,1003,501,2025-07-08,9296,2024-12-15,2025-01-11,Adam,Fahmy,6.0,Zamalek,Active,2025-07-12,Adventure,128,2017.0,Nile Press
201,1003,501,2025-07-08,9052,2024-06-20,2024-06-29,Mostafa,Wahba,6.0,Maadi,Inactive,2024-07-20,Adventure,128,2017.0,Nile Press
250,1017,507,2025-07-11,9334,2025-12-20,2026-01-05,Adam,Fahmy,6.0,Zamalek,Active,2025-07-12,Science,160,2024.0,Nile Press

In [58]:
final_combined=final_combined.drop_duplicates(subset=['book_id', 'checkout_id', 'member_id'])

In [59]:
final_combined.shape

(256, 16)

In [60]:
final_combined.duplicated().sum()

np.int64(0)

In [61]:
final_combined['member_id'].value_counts()

member_id
1003    55
1017    54
1005    45
1062    25
1201     9
1022     8
1049     8
1026     8
1007     8
1058     8
1009     8
1002     6
1150     5
1104     5
1055     3
1029     1
Name: count, dtype: int64

In [62]:
final_combined.isna().sum()

member_id            0
book_id              0
checkout_date_x      0
checkout_id          0
checkout_date_y      0
return_date          0
first_name           0
last_name            0
grade                0
neighborhood         0
membership_status    0
join_date            0
genre                0
pages                0
publication_year     0
publisher            0
dtype: int64

In [63]:
final_combined.shape

(256, 16)

In [64]:
final_combined.head()

,member_id,book_id,checkout_date_x,checkout_id,checkout_date_y,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher
0,1026,522,2025-07-11,9033,2025-02-26,2025-03-11,Rana,Fouad,6.0,Maadi,Active,2025-12-04,Mystery,104,2016.0,Cairo Young Readers
1,1026,522,2025-07-11,9274,2024-09-06,2024-09-17,Retaj,Fahmy,6.0,Heliopolis,Inactive,2024-03-21,Mystery,104,2016.0,Cairo Young Readers
2,1026,522,2025-07-11,9332,2024-07-03,2026-01-05,Tarek,Adel,7.0,Zamalek,Active,2023-01-22,Mystery,104,2016.0,Cairo Young Readers
3,1026,522,2025-07-11,9121,2025-02-24,2025-03-14,Mostafa,Fouad,9.0,Nasr City,Active,2023-09-25,Mystery,104,2016.0,Cairo Young Readers
4,1026,522,2025-07-11,9314,2024-08-13,2024-09-02,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Mystery,104,2016.0,Cairo Young Readers

In [65]:
final_combined.to_csv("30911221300529-Library_task1_combined_data.csv", index=False)

In [66]:
final_combined.isna().sum()

member_id            0
book_id              0
checkout_date_x      0
checkout_id          0
checkout_date_y      0
return_date          0
first_name           0
last_name            0
grade                0
neighborhood         0
membership_status    0
join_date            0
genre                0
pages                0
publication_year     0
publisher            0
dtype: int64

In [67]:
final_combined.isna().sum().sum()

np.int64(0)

In [68]:
final_combined.duplicated().sum()

np.int64(0)

In [69]:
final_combined.shape

(256, 16)

In [70]:
final_combined.head()

,member_id,book_id,checkout_date_x,checkout_id,checkout_date_y,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher
0,1026,522,2025-07-11,9033,2025-02-26,2025-03-11,Rana,Fouad,6.0,Maadi,Active,2025-12-04,Mystery,104,2016.0,Cairo Young Readers
1,1026,522,2025-07-11,9274,2024-09-06,2024-09-17,Retaj,Fahmy,6.0,Heliopolis,Inactive,2024-03-21,Mystery,104,2016.0,Cairo Young Readers
2,1026,522,2025-07-11,9332,2024-07-03,2026-01-05,Tarek,Adel,7.0,Zamalek,Active,2023-01-22,Mystery,104,2016.0,Cairo Young Readers
3,1026,522,2025-07-11,9121,2025-02-24,2025-03-14,Mostafa,Fouad,9.0,Nasr City,Active,2023-09-25,Mystery,104,2016.0,Cairo Young Readers
4,1026,522,2025-07-11,9314,2024-08-13,2024-09-02,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Mystery,104,2016.0,Cairo Young Readers

In [71]:
df = pd.read_csv("/content/30911221300529-Library_task1_combined_data.csv")
df

,member_id,book_id,checkout_date_x,checkout_id,checkout_date_y,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher
0,1026,522,2025-07-11,9033,2025-02-26,2025-03-11,Rana,Fouad,6.0,Maadi,Active,2025-12-04,Mystery,104,2016.0,Cairo Young Readers
1,1026,522,2025-07-11,9274,2024-09-06,2024-09-17,Retaj,Fahmy,6.0,Heliopolis,Inactive,2024-03-21,Mystery,104,2016.0,Cairo Young Readers
2,1026,522,2025-07-11,9332,2024-07-03,2026-01-05,Tarek,Adel,7.0,Zamalek,Active,2023-01-22,Mystery,104,2016.0,Cairo Young Readers
3,1026,522,2025-07-11,9121,2025-02-24,2025-03-14,Mostafa,Fouad,9.0,Nasr City,Active,2023-09-25,Mystery,104,2016.0,Cairo Young Readers
4,1026,522,2025-07-11,9314,2024-08-13,2024-09-02,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Mystery,104,2016.0,Cairo Young Readers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,1017,507,2025-07-11,9377,2025-03-25,2025-04-06,Aya,Wahba,9.0,Nasr City,Active,2025-01-22,Science,160,2024.0,Nile Press
252,1017,507,2025-07-11,9210,2025-09-11,2025-09-29,Sherif,Saleh,7.0,Heliopolis,active,2024-02-19,Science,160,2024.0,Nile Press
253,1017,507,2025-07-11,9028,2025-01-19,2025-01-28,Adam,Badr,9.0,Maadi,Active,2025-07-12,Science,160,2024.0,Nile Press
254,1017,507,2025-07-11,9311,2025-06-26,2025-07-09,Adam,Fahmy,6.0,Zamalek,Active,2025-07-12,Science,160,2024.0,Nile Press
255,1017,507,2025-07-11,9164,2024-12-02,2024-12-12,Aya,Wahba,9.0,Nasr City,Active,2025-01-22,Science,160,2024.0,Nile Press

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256 entries, 0 to 255
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   member_id          256 non-null    int64
 1   book_id            256 non-null    int64
 2   checkout_date_x    256 non-null    object
 3   checkout_id        256 non-null    int64
 4   checkout_date_y    256 non-null    object
 5   return_date        256 non-null    object
 6   first_name         256 non-null    object
 7   last_name          256 non-null    object
 8   grade              256 non-null    float64
 9   neighborhood       256 non-null    object
 10  membership_status  256 non-null    object
 11  join_date          256 non-null    object
 12  genre              256 non-null    object
 13  pages              256 non-null    int64
 14  publication_year   256 non-null    float64
 15  publisher          256 non-null    object
dtypes: float64(2), int64(4), object(10)
memory usage: 32.1+ KB

In [73]:
df["neighborhood"].value_counts()

neighborhood
Maadi         65
Nasr City     58
Heliopolis    52
Zamalek       43
Shubra        21
Maadi         10
zamalek        5
NASR CITY      1
HELIOPOLIS     1
Name: count, dtype: int64

In [74]:
df.shape

(256, 16)

In [75]:
df["neighborhood"]=df["neighborhood"].str.title().str.strip()

In [76]:
df["neighborhood"].value_counts()

neighborhood
Maadi         75
Nasr City     59
Heliopolis    53
Zamalek       48
Shubra        21
Name: count, dtype: int64

In [77]:
df['membership_status'].value_counts()

membership_status
Active      170
Inactive     36
active       31
inactive     19
Name: count, dtype: int64

In [78]:
df['membership_status'].str.strip().str.title()

0        Active
1      Inactive
2        Active
3        Active
4        Active
         ...
251      Active
252      Active
253      Active
254      Active
255      Active
Name: membership_status, Length: 256, dtype: object

In [79]:
df.shape

(256, 16)

In [80]:
df['member_id'].duplicated().sum().sum()

np.int64(240)

In [81]:
inactive_df = df[df['membership_status'] == 'Inactive']
print(len(inactive_df))
inactive_df.head()

36

,member_id,book_id,checkout_date_x,checkout_id,checkout_date_y,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher
1,1026,522,2025-07-11,9274,2024-09-06,2024-09-17,Retaj,Fahmy,6.0,Heliopolis,Inactive,2024-03-21,Mystery,104,2016.0,Cairo Young Readers
12,1049,520,2025-07-11,9242,2025-06-01,2025-07-01,Sara,Rashad,8.0,Heliopolis,Inactive,2024-06-25,Science Fiction,136,2009.0,Oasis Books
26,1062,525,2025-07-05,9182,2024-05-19,2024-06-03,Retaj,Kamel,8.0,Nasr City,Inactive,2023-08-26,Adventure,297,2015.0,Oasis Books
29,1062,525,2025-07-05,9055,2025-08-08,2025-08-27,Hamza,Sabry,7.0,Maadi,Inactive,2025-08-13,Adventure,297,2015.0,Oasis Books
51,1009,503,2025-07-09,9268,2025-06-16,2025-07-14,Sara,Rashad,8.0,Heliopolis,Inactive,2024-06-25,Historical,259,2017.0,Nile Press

In [82]:
inactive_df.head()

,member_id,book_id,checkout_date_x,checkout_id,checkout_date_y,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher
1,1026,522,2025-07-11,9274,2024-09-06,2024-09-17,Retaj,Fahmy,6.0,Heliopolis,Inactive,2024-03-21,Mystery,104,2016.0,Cairo Young Readers
12,1049,520,2025-07-11,9242,2025-06-01,2025-07-01,Sara,Rashad,8.0,Heliopolis,Inactive,2024-06-25,Science Fiction,136,2009.0,Oasis Books
26,1062,525,2025-07-05,9182,2024-05-19,2024-06-03,Retaj,Kamel,8.0,Nasr City,Inactive,2023-08-26,Adventure,297,2015.0,Oasis Books
29,1062,525,2025-07-05,9055,2025-08-08,2025-08-27,Hamza,Sabry,7.0,Maadi,Inactive,2025-08-13,Adventure,297,2015.0,Oasis Books
51,1009,503,2025-07-09,9268,2025-06-16,2025-07-14,Sara,Rashad,8.0,Heliopolis,Inactive,2024-06-25,Historical,259,2017.0,Nile Press

In [83]:
active_members = df[df['membership_status']=='Active']
print(len(active_members))
active_members.head()

170

,member_id,book_id,checkout_date_x,checkout_id,checkout_date_y,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher
0,1026,522,2025-07-11,9033,2025-02-26,2025-03-11,Rana,Fouad,6.0,Maadi,Active,2025-12-04,Mystery,104,2016.0,Cairo Young Readers
2,1026,522,2025-07-11,9332,2024-07-03,2026-01-05,Tarek,Adel,7.0,Zamalek,Active,2023-01-22,Mystery,104,2016.0,Cairo Young Readers
3,1026,522,2025-07-11,9121,2025-02-24,2025-03-14,Mostafa,Fouad,9.0,Nasr City,Active,2023-09-25,Mystery,104,2016.0,Cairo Young Readers
4,1026,522,2025-07-11,9314,2024-08-13,2024-09-02,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Mystery,104,2016.0,Cairo Young Readers
5,1026,522,2025-07-11,9289,2025-09-09,2025-09-19,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Mystery,104,2016.0,Cairo Young Readers

In [84]:
inactive_members = inactive_df['membership_status']
print(len(inactive_members))
inactive_members.head()

36

1     Inactive
12    Inactive
26    Inactive
29    Inactive
51    Inactive
Name: membership_status, dtype: object

In [85]:
members = df['member_id']
members.head()

0    1026
1    1026
2    1026
3    1026
4    1026
Name: member_id, dtype: int64

In [86]:
df['member_id'].unique()

array([1026, 1049, 1062, 1104, 1009, 1022, 1029, 1201, 1005, 1058, 1002,
       1150, 1055, 1007, 1003, 1017])

In [87]:
inactive_members_status_by_id = inactive_df.groupby('member_id')['membership_status'].unique().reset_index()
inactive_members_status_by_id

    member_id membership_status
0        1003        [Inactive]
1        1005        [Inactive]
2        1007        [Inactive]
3        1009        [Inactive]
4        1017        [Inactive]
5        1022        [Inactive]
6        1026        [Inactive]
7        1049        [Inactive]
8        1062        [Inactive]
9        1150        [Inactive]
10       1201        [Inactive]

In [90]:
neighborhood_by_members = df.groupby('neighborhood')['member_id'].nunique()
print("neighborhood_by_members\n\n", neighborhood_by_members)

neighborhood_by_members

 neighborhood
Heliopolis    13
Maadi         14
Nasr City     13
Shubra         8
Zamalek       12
Name: member_id, dtype: int64

In [91]:
neighborhood_by_checkouts = df.groupby('neighborhood')['checkout_id'].nunique()
print("neighborhood_by_checkouts\n\n", neighborhood_by_checkouts)

neighborhood_by_checkouts

 neighborhood
Heliopolis    53
Maadi         75
Nasr City     59
Shubra        21
Zamalek       48
Name: checkout_id, dtype: int64

In [94]:
df.to_csv("30911221300529-Library_task2_cleaned_data.csv", index=False)

In [95]:
df = pd.read_csv("/content/30911221300529-Library_task2_cleaned_data.csv")
df.head()

,member_id,book_id,checkout_date_x,checkout_id,checkout_date_y,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher
0,1026,522,2025-07-11,9033,2025-02-26,2025-03-11,Rana,Fouad,6.0,Maadi,Active,2025-12-04,Mystery,104,2016.0,Cairo Young Readers
1,1026,522,2025-07-11,9274,2024-09-06,2024-09-17,Retaj,Fahmy,6.0,Heliopolis,Inactive,2024-03-21,Mystery,104,2016.0,Cairo Young Readers
2,1026,522,2025-07-11,9332,2024-07-03,2026-01-05,Tarek,Adel,7.0,Zamalek,Active,2023-01-22,Mystery,104,2016.0,Cairo Young Readers
3,1026,522,2025-07-11,9121,2025-02-24,2025-03-14,Mostafa,Fouad,9.0,Nasr City,Active,2023-09-25,Mystery,104,2016.0,Cairo Young Readers
4,1026,522,2025-07-11,9314,2024-08-13,2024-09-02,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Mystery,104,2016.0,Cairo Young Readers